// Auto generated by version-config - DO NOT EDIT
#ifndef ossimVersion_HEADER
#define ossimVersion_HEADER

#include <ossim/ossimConfig.h>

#ifndef OSSIM_VERSION
#  define OSSIM_VERSION "Version 1.8.4"
#  define OSSIM_VERSION_NUMBER "1.8.4"
#  define OSSIM_MAJOR_VERSION_NUMBER 1
#  define OSSIM_MINOR_VERSION_NUMBER 8
#  define OSSIM_RELEASE_NUMBER 4
#endif

// date format = (yyyymmdd)
#ifndef OSSIM_BUILD_DATE
#  define OSSIM_BUILD_DATE "(20110920)"
#endif

#endif /* End of #ifndef ossimVersion_HEADER */
