//*******************************************************************
//
// License:  See top level LICENSE.txt file.
// 
// Author: Garrett Potts (gpotts@imagelinks.com)
// 
//********************************************************************
// $Id: rspfRpfConstants.h 9967 2006-11-29 02:01:23Z gpotts $
//
#ifndef rspfRpfComponentId_HEADER
#define rspfRpfComponentId_HEADER

const unsigned long RSPF_RPF_ULONG_NULL = 0xFFFFFFFF;

enum rspfRpfComponentId
{
   RSPF_RPF_HEADER_COMPONENT   = 128,
   RSPF_RPF_LOCATION_COMPONENT = 129,
   RSPF_RPF_COVERAGE_SECTION_SUBHEADER = 130,
   RSPF_RPF_COMPRESSION_SECTION_SUBHEADER = 131,
   RSPF_RPF_COMPRESION_LOOKUP_SUBSECTION = 132,
   RSPF_RPF_COMPRESION_PARAMETER_SUBSECTION = 133,
   RSPF_RPF_COLOR_GRAYSCALE_SECTION_SUBHEADER = 134,
   RSPF_RPF_COLORMAP_SUBSECTION = 135,
   RSPF_RPF_IMAGE_DESCRIPTION_SUBHEADER = 136,
   RSPF_RPF_IMAGE_DISPLAY_PARAMETERS_SUBHEADER = 137,
   RSPF_RPF_MASK_SUBSECTION = 138,
   RSPF_RPF_COLOR_CONVERTER_SUBSECTION = 139,
   RSPF_RPF_SPATIAL_DATA_SUBSECTION = 140,
   RSPF_RPF_ATTRIBUTE_SECTION_SUBHEADER = 141,
   RSPF_RPF_ATTRIBUTE_SUBSECTION = 142,
   RSPF_RPF_EXPLICIT_AREAL_COVERAGE_TABLE = 143,
   RSPF_RPF_RELATED_IMAGES_SECTION_SUBHEADER = 144,
   RSPF_RPF_RELATED_IMAGES_SUBSECTION = 145,
   RSPF_RPF_REPLACE_UPDATE_SECTION_SUBHEADER = 146,
   RSPF_RPF_REPLACE_UPDATE_TABLE = 147,
   RSPF_RPF_BOUNDARY_RECT_SECTION_SUBHEADER = 148,
   RSPF_RPF_BOUNDARY_RECT_TABLE = 149,
   RSPF_RPF_FRAME_FILE_INDEX_SECTION_SUBHEADER = 150,
   RSPF_RPF_FRAME_FILE_INDEX_SUBSECTION = 151,
   RSPF_RPF_COLOR_TABLE_INDEX_SECTION_SUBHEADER = 152,
   RSPF_RPF_COLOR_TABLE_INDEX_RECORD = 153
};

#endif
