// Auto generated by version-config - DO NOT EDIT
#ifndef rspfVersion_HEADER
#define rspfVersion_HEADER

#include <rspf/rspfConfig.h>

#ifndef RSPF_VERSION
#  define RSPF_VERSION "Version 1.8.4"
#  define RSPF_VERSION_NUMBER "1.8.4"
#  define RSPF_MAJOR_VERSION_NUMBER 1
#  define RSPF_MINOR_VERSION_NUMBER 8
#  define RSPF_RELEASE_NUMBER 4
#endif

// date format = (yyyymmdd)
#ifndef RSPF_BUILD_DATE
#  define RSPF_BUILD_DATE "(20110920)"
#endif

#endif /* End of #ifndef rspfVersion_HEADER */
