###
# $Id: makefile.vc 9232 2006-07-05 21:42:47Z dburken $
#
# Windows nmake make file.
###
RSPF_ROOT	=	..\..\..
!INCLUDE $(RSPF_ROOT)\nmake.opt

OBJ = \
booleng.obj \
graph.obj \
graphlst.obj \
line.obj \
link.obj \
lpoint.obj \
node.obj \
record.obj \
scanbeam.obj

default:	$(OBJ)

clean:
	$(RM) *.obj
